-- RESTAURA EXATAMENTE o ACL das 4 views e das 7 RPCs encontrado na produção ANTES da migration 115 (consulta 6b8, 11/10/2026).
-- Só reabre o que existia. USO: apenas com aprovação escrita (reabre acesso direto de anon/authenticated/PUBLIC). Executar como postgres.
begin;
set local lock_timeout = '5s';
grant execute on function public.bonificacao_congelar_competencia(uuid,uuid,integer,integer,text,jsonb,jsonb,text,uuid,text) to public;
grant execute on function public.bonificacao_congelar_competencia(uuid,uuid,integer,integer,text,jsonb,jsonb,text,uuid,text) to anon;
grant execute on function public.bonificacao_congelar_competencia(uuid,uuid,integer,integer,text,jsonb,jsonb,text,uuid,text) to authenticated;
grant execute on function public.bonificacao_congelar_competencia(uuid,uuid,integer,integer,text,jsonb,jsonb,text,uuid,text) to service_role;
grant execute on function public.bonificacao_reabrir_competencia(uuid,integer,integer,text,uuid,text) to public;
grant execute on function public.bonificacao_reabrir_competencia(uuid,integer,integer,text,uuid,text) to anon;
grant execute on function public.bonificacao_reabrir_competencia(uuid,integer,integer,text,uuid,text) to authenticated;
grant execute on function public.bonificacao_reabrir_competencia(uuid,integer,integer,text,uuid,text) to service_role;
grant execute on function public.converter_empresa_para_unidade(uuid,uuid,uuid,text,text,text) to public;
grant execute on function public.converter_empresa_para_unidade(uuid,uuid,uuid,text,text,text) to anon;
grant execute on function public.converter_empresa_para_unidade(uuid,uuid,uuid,text,text,text) to authenticated;
grant execute on function public.converter_empresa_para_unidade(uuid,uuid,uuid,text,text,text) to service_role;
grant execute on function public.excluir_organizacao_definitivamente(uuid,text,uuid,text,text,text) to public;
grant execute on function public.excluir_organizacao_definitivamente(uuid,text,uuid,text,text,text) to anon;
grant execute on function public.excluir_organizacao_definitivamente(uuid,text,uuid,text,text,text) to authenticated;
grant execute on function public.excluir_organizacao_definitivamente(uuid,text,uuid,text,text,text) to service_role;
grant execute on function public.promover_unidade_para_empresa(uuid,text,uuid,text,text,text) to public;
grant execute on function public.promover_unidade_para_empresa(uuid,text,uuid,text,text,text) to anon;
grant execute on function public.promover_unidade_para_empresa(uuid,text,uuid,text,text,text) to authenticated;
grant execute on function public.promover_unidade_para_empresa(uuid,text,uuid,text,text,text) to service_role;
grant execute on function public.remapear_organizacao_em_tabelas_de_unidade(uuid,uuid,uuid) to public;
grant execute on function public.remapear_organizacao_em_tabelas_de_unidade(uuid,uuid,uuid) to anon;
grant execute on function public.remapear_organizacao_em_tabelas_de_unidade(uuid,uuid,uuid) to authenticated;
grant execute on function public.remapear_organizacao_em_tabelas_de_unidade(uuid,uuid,uuid) to service_role;
grant execute on function public.transferir_unidade_organizacao(uuid,uuid,uuid,text,text,text) to public;
grant execute on function public.transferir_unidade_organizacao(uuid,uuid,uuid,text,text,text) to anon;
grant execute on function public.transferir_unidade_organizacao(uuid,uuid,uuid,text,text,text) to authenticated;
grant execute on function public.transferir_unidade_organizacao(uuid,uuid,uuid,text,text,text) to service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_estoque_critico to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_estoque_critico to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_estoque_critico to service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_faturamento_diario to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_faturamento_diario to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_faturamento_diario to service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_produto_margem to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_produto_margem to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_produto_margem to service_role;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_produtos_vendidos to anon;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_produtos_vendidos to authenticated;
grant DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.vw_produtos_vendidos to service_role;
commit;
